export type Patient = {
  age: string | null;
  balance: string | null;
  cnicNo: string | null;
  contactNo: string | null;
  createdAt: Date;
  data: string | null;
  discountPercentage: string | null;
  discountRupees: string | null;
  email: string | null;
  gender: string | null;
  id: string;
  mrNo: string | null;
  name: string | null;
  paid: string | null;
  password: string | null;
  pinNo: string | null;
  referBy: string | null;
  time: string | null;
  total: string | null;
  updatedAt: Date;
  username: string | null;
};
